server:
  port: 8082

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./empik-db
    username: empik
    password: empik
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true